package ru.stqa.pft.addressbook;// Generated by Selenium IDE


import org.testng.annotations.Test;
public class CreateGroupTest extends TestBase {

  @Test
  public void creategroup() {
    gotoGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("test", "test1", "test2"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
