package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.model.GroupData;

import java.util.List;


public class GroupDeletionTest extends TestBase {

  @Test
  public void groupDeletion() {
    app.navigationBar().clickOnGroups();
    if (! app.groupPage().isThereAGroup()); {
      app.groupPage().createGroup(new GroupData("test", null, null));
    }
    List<GroupData> before = app.groupPage().groupList();
    app.groupPage().selectGroup(before.size() - 1);
    app.groupPage().deleteSelectedGroups();
    app.groupPage().returnToGroupPage();
    List<GroupData> after = app.groupPage().groupList();
    Assert.assertEquals(after.size(), before.size() - 1);

    before.remove(before.size() - 1);
      Assert.assertEquals(before, after);


  }

}

